"""Add slug field for Post and Category models

Revision ID: 20b08a42c990
Revises: d4ec2ccd19b2
Create Date: 2026-02-19 18:27:55.864512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20b08a42c990'
down_revision: Union[str, Sequence[str], None] = 'd4ec2ccd19b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('slug', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.add_column('posts', sa.Column('slug', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_posts_slug'), 'posts', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_slug'), table_name='posts')
    op.drop_column('posts', 'slug')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_column('categories', 'slug')
    # ### end Alembic commands ###
